//CTA PACIENTE RITA, Y ELVA FALCON
SELECT COUNT(*) FROM CRED_CTACTE WHERE (LOGIN(ID_PERSONAL_USER) LIKE '%ritar%' OR LOGIN(ID_PERSONAL_USER) = 'efalcon') and TO_CHAR(fecha_creacion, 'YYYYMM') = '202405';
